# services: 
#   - docker

# before_install:
#   - docker build -t guseman/docker-react -f Dockerfile.dev .

# script:
#   - docker run -e CI=true guseman/docker-react npm run test

# deploy:
#   provider: elasticbeanstalk
#   region: us-west-2
#   app: "docker"
#   env: "Docker-env"
#   bucket_name: "elasticbeanstalk-us-west-2-962832698168"
#   bucket_path: "docker-react"
# on:
#   branch: master

# access_key_id: $AWS_ACCESS_KEY_ID
# secret_access_key: $AWS_SECRET_ACCESS_KEY

# Define environment
dist: xenial # Ubuntu 16.04
language: bash

# Export variables
env:
  - tf_version=0.12.19 tf_init_cli_options="-input=false" tf_validation_cli_options="" tf_plan_cli_options="-lock=false -input=false" tf_apply_cli_options="-auto-approve -input=false"

# Only build pushes to master branch
branches:
  only:
    - master


# Install dependencies
before_install:
  - wget https://releases.hashicorp.com/terraform/"$tf_version"/terraform_"$tf_version"_linux_amd64.zip
  - unzip terraform_"$tf_version"_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_"$tf_version"_linux_amd64.zip

  # Terraform Plan and Apply
# Plan only on pull requests, Apply on merged code
jobs:
  include:
    - stage: terraform plan
      # Only run terraform validate and plan state if within a pull request
      if: type IN (pull_request)
      script:
        - echo "Executing Terraform Plan on pull request code"
        - terraform init $tf_init_cli_options
        - terraform validate $tf_validation_cli_options
        - terraform plan $tf_plan_cli_options
    - stage: terraform apply
      # Only run terraform apply stage if outside of a pull request
      if: type IN (push) and branch = master
      script:
        - echo "Executing Terraform Apply on merged code"
        - terraform init $tf_init_cli_options
        - terraform apply $tf_apply_cli_options

